version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Root directory (where pyproject.toml is)
    schedule:
      interval: "hourly"
    open-pull-requests-limit: 10
    reviewers:
      - "MicahBest"
    labels:
      - "dependencies"
