version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Root directory (where pyproject.toml is)
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
