[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "testpypackage"
version = "0.1.0"
description = "A test Python package"
authors = [{ name = "Your Name", email = "you@example.com" }]
license = { text = "MIT" }
dependencies = []

[tool.pytest.ini_options]
testpaths = ["tests"]
