name: Dependabot Auto-merge

on:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Checking token access..."
      - name: Debug Token Access
        run: echo "Token Length: $(echo -n "${{ secrets.AUTO_MERGE_TOKEN }}" | wc -c)"

      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.AUTO_MERGE_TOKEN }}
