name: Dependabot Auto-merge

on:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          command: squash and merge
          github-token: ${{ secrets.AUTO_MERGE_TOKEN }}
