name: Dependabot Auto Merge

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 6 PM CST (0 AM UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Dependabot Auto Merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2.6.6
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            target: minor  # Merge only minor updates
            approve: true  # Approve PR before merging
            command: merge  # Merge the PR
